### PR TITLE
Add Edlib from https://github.com/Martinsos/edlib

### PR DESCRIPTION
**Pull request by pkufool**
- [ ] Add python wrapper using pybind11

### CODE REVIEW

**Comment by pkufool** [comment]
@danpovey  Could I bind this version (i.e. the original verision supporting only char*) to python first, accepting only byte array from python?  For example, the output of `"text".encoder("utf-8")`.

**Comment by danpovey** [comment]
OK.
But now I am starting to wonder whether it might have been a mistake to use edlib.  After our conversation yesterday, it seems edlib uses an algorithm relying onbitmaps of length (num_symbols), and the speed advantages of it might mostly be limited to small vocabularies (e.g. DNA base, proteins).
I'm wondering whether it might make sense to replace it with something else (but trying to figure what algorithm would not use too much memory but also would be reasonably fast.)

**Comment by danpovey** [comment]
By the way, I think I figured out how we could code a conventional Levenshtein alignment (or the modified one where the query string can start and stop at any position in the reference), without using very much memory.  It would be based on the two-array algorithm for computing Levenshtein distance (the one that doesn't compute an alignment), but instead of costs inside those two arrays, there would be something like this:
<code>
  struct Backtrace {
     int64_t bitmap;  // bitmap records shape of most recent backtrace, where every time we consume a query symbol we do:
                                // self.bitmap |= (1 << (num_bits++));   and every time we consume a reference symbol we do:
                                // self.bitmap  |= (0 << (num_bits++));  which can be optimized to: num_bits++;  When num_bits
                                // reaches 64 we allocate a DynamicBacktrace object and reset it to 0.
     int32_t num_bits;
     std::shared_ptr<DynamicBacktrace> prev;
  };
  struct DynamicBacktrace {
      std::shared_ptr<DynamicBacktrace> prev;
      int64_t bitmap;
  };
  struct LevensheinElement {
    int cost;
    Backtrace backtrace;
 } ;
</code>

**Comment by pkufool** [comment]
Close this PR since it only support int8 which is not suitable for us.

**Pull request closed without merging**
