### PR TITLE
Implement transcript

### PR DESCRIPTION
**Pull request by csukuangfj**

### CODE REVIEW

**Comment by danpovey** [comment]
Looks good, thanks!
For your example, I think it's BPE tokens with the special underscore as word separators, and you are just appending them.
Is the idea that we use other operations, later on, to do the normalizations (underscore to space)?  That would be fine, just checking that we are on the same page.

**Comment by csukuangfj** [comment]
> Looks good, thanks! For your example, I think it's BPE tokens with the special underscore as word separators, and you are just appending them. Is the idea that we use other operations, later on, to do the normalizations (underscore to space)? That would be fine, just checking that we are on the same page.

Underscore here is just like a normal symbol. we can replace it with a space later on if needed.

**Comment by danpovey** [comment]
OK.

**Comment by csukuangfj** [comment]
Thanks! I am merging it and working on `class SourcedText`.

**Pull request merged**
